In [2]:
import pandas as pd
data=pd.read_csv("Airbnb_Open_Data.csv")
data.head()

C:\Users\Office\AppData\Local\Temp\ipykernel_12732\4231346580.py:2: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv("Airbnb_Open_Data.csv")

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [3]:
data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

In [6]:
# the license has 2 non-null
data['license'] # there are many null values

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
102594    NaN
102595    NaN
102596    NaN
102597    NaN
102598    NaN
Name: license, Length: 102599, dtype: object

In [ ]:
""" Deleting redundant columns.Renaming the columns.Dropping duplicates.cleaning indv columns. remove null values """

In [7]:
data

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [8]:
data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [34]:
col_keep=[ 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number_of_reviews', 'last review'] # useful columns so i can do my analysis process through em 
col_drop=['reviews_per_month',
       'review_rate_number', 'calculated_host_listings_count',
       'availability_365', 'house_rules', 'license','id'] # useless columns that i cannot do my process through em

In [10]:
len(col_keep) # 19 cols

19

In [11]:
len(col_drop) # 7 cols

7

In [16]:
# filtering data 
df = data[col_keep]

In [17]:
df

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN

In [41]:
# dropping cols 
data.drop(columns=col_drop,inplace=True
         # deleted the unwanted columns from prev step

KeyError: "['reviews_per_month', 'review_rate_number', 'calculated_host_listings_count', 'availability_365', 'house_rules', 'license', 'id'] not found in axis"

In [40]:
data.shape

(102599, 19)

In [45]:
"""Rename the columns , dropping duplicates , cleaning indivduals columns ,remove the nan values"""
data.columns
# NAME -> Name
data.rename(columns={"NAME":"Name"},inplace=True) # renamed the NAME called n made it better ( as a title )

In [47]:
data.columns

Index(['Name', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review'],
      dtype='object')

In [51]:
new_col=[]
for i in data.columns:
    new_col.append(i.upper())
print(new_col)

['NAME', 'HOST ID', 'HOST_IDENTITY_VERIFIED', 'HOST NAME', 'NEIGHBOURHOOD GROUP', 'NEIGHBOURHOOD', 'LAT', 'LONG', 'COUNTRY', 'COUNTRY CODE', 'INSTANT_BOOKABLE', 'CANCELLATION_POLICY', 'ROOM TYPE', 'CONSTRUCTION YEAR', 'PRICE', 'SERVICE FEE', 'MINIMUM NIGHTS', 'NUMBER OF REVIEWS', 'LAST REVIEW']

In [56]:
new_df=data.copy()
new_df.columns=new_col
# changed the new_df columns name to new_col (capital letters columns )

In [55]:
new_df.columns

Index(['NAME', 'HOST ID', 'HOST_IDENTITY_VERIFIED', 'HOST NAME',
       'NEIGHBOURHOOD GROUP', 'NEIGHBOURHOOD', 'LAT', 'LONG', 'COUNTRY',
       'COUNTRY CODE', 'INSTANT_BOOKABLE', 'CANCELLATION_POLICY', 'ROOM TYPE',
       'CONSTRUCTION YEAR', 'PRICE', 'SERVICE FEE', 'MINIMUM NIGHTS',
       'NUMBER OF REVIEWS', 'LAST REVIEW'],
      dtype='object')

In [57]:
data

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN

In [60]:
# duplicates
data.duplicated().sum() # 541 rows duplicated
data.duplicated().value_counts() # 102058 not duplicated & 541 duplicated columns

False    102058
True        541
Name: count, dtype: int64

In [62]:
data.drop_duplicates(inplace = True)

In [64]:
data.duplicated().sum() # i have no duplicated now

np.int64(0)

In [65]:
data

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102053,Cozy bright room near Prospect Park,77326652202,unconfirmed,Mariam,Brooklyn,Flatbush,40.64945,-73.96108,United States,US,True,moderate,Private room,NaN,$696,NaN,7.0,12.0,3/27/2019
102054,Private Bedroom with Amazing Rooftop View,45936254757,verified,Trey,Brooklyn,Bushwick,40.69872,-73.92718,United States,US,False,flexible,Private room,NaN,$909,NaN,1.0,19.0,8/31/2017
102055,Pretty Brooklyn One-Bedroom for 2 to 4 people,23801060917,verified,Michael,Brooklyn,Bedford-Stuyvesant,40.67810,-73.90822,United States,US,True,moderate,Entire home/apt,NaN,$387,NaN,2.0,50.0,6/26/2019
102056,Room & private bathroom in historic Harlem,15593031571,unconfirmed,Shireen,Manhattan,Harlem,40.81248,-73.94317,United States,US,True,strict,Private room,NaN,$848,NaN,2.0,0.0,NaN
102057,Rosalee Stewart,93578954226,verified,Stanley,Manhattan,Harlem,40.81315,-73.94747,United States,US,False,flexible,Entire home/apt,2011.0,"$1,128",NaN,4.0,22.0,6/15/2019

In [67]:
data.isna().sum()

Name                        250
host id                       0
host_identity_verified      289
host name                   404
neighbourhood group          29
neighbourhood                16
lat                           8
long                          8
country                     532
country code                131
instant_bookable            105
cancellation_policy          76
room type                     0
Construction year           214
price                       247
service fee                 273
minimum nights              400
number of reviews           183
last review               15832
dtype: int64

In [68]:
data.drop(columns=["last review"],inplace=True) # the last review has like 15k null values its useless

In [69]:
data.isna().sum()

Name                      250
host id                     0
host_identity_verified    289
host name                 404
neighbourhood group        29
neighbourhood              16
lat                         8
long                        8
country                   532
country code              131
instant_bookable          105
cancellation_policy        76
room type                   0
Construction year         214
price                     247
service fee               273
minimum nights            400
number of reviews         183
dtype: int64

In [70]:
fill_values={"Name":"unknown","host_identity_verified":"unknown","host name":"unknown","neighbourhood group":"unknown","neighbourhood":"unknown","country":"unknown","country code":"unknown","instant_bookable":"unknown","cancellation_policy":"unknown"}
data.fillna(fill_values, inplace=True)

In [71]:
data.isna().sum()

Name                        0
host id                     0
host_identity_verified      0
host name                   0
neighbourhood group         0
neighbourhood               0
lat                         8
long                        8
country                     0
country code                0
instant_bookable            0
cancellation_policy         0
room type                   0
Construction year         214
price                     247
service fee               273
minimum nights            400
number of reviews         183
dtype: int64

In [72]:
data.dropna(inplace=True)

In [73]:
data.isna().sum() # now having 0 null values !!

Name                      0
host id                   0
host_identity_verified    0
host name                 0
neighbourhood group       0
neighbourhood             0
lat                       0
long                      0
country                   0
country code              0
instant_bookable          0
cancellation_policy       0
room type                 0
Construction year         0
price                     0
service fee               0
minimum nights            0
number of reviews         0
dtype: int64

In [74]:
data

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,unknown,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0
3,unknown,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102040,"Room in Queens, NY, near LGA.",56457739998,verified,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,True,strict,Private room,2022.0,$982,$196,1.0,239.0
102041,Cozy home away from home,60176837202,verified,unknown,Queens,Edgemere,40.59380,-73.77373,United States,US,True,moderate,Private room,2020.0,$946,$189,1.0,76.0
102042,Central Park Views - Private Room & Bathroom,68411243647,verified,unknown,Manhattan,Upper West Side,40.79712,-73.96117,United States,US,False,strict,Private room,2012.0,$706,$141,1.0,4.0
102043,Ultimate 50th Floor Downtown Penthouse - 4000...,95625271612,verified,unknown,Manhattan,SoHo,40.72318,-74.00223,United States,US,False,flexible,Entire home/apt,2020.0,"$1,043",$209,2.0,21.0
102044,Lovely Two Bedroom & Event Space From Nonprofit,83006936257,verified,unknown,Brooklyn,Bedford-Stuyvesant,40.69095,-73.93444,United States,US,False,flexible,Entire home/apt,2010.0,$809,$162,31.0,4.0

In [78]:
data["host_identity_verified"]=data["host_identity_verified"].str.upper()

In [79]:
data

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,UNKNOWN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0
3,unknown,85098326012,UNCONFIRMED,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,True,strict,Private room,2022.0,$982,$196,1.0,239.0
102041,Cozy home away from home,60176837202,VERIFIED,unknown,Queens,Edgemere,40.59380,-73.77373,United States,US,True,moderate,Private room,2020.0,$946,$189,1.0,76.0
102042,Central Park Views - Private Room & Bathroom,68411243647,VERIFIED,unknown,Manhattan,Upper West Side,40.79712,-73.96117,United States,US,False,strict,Private room,2012.0,$706,$141,1.0,4.0
102043,Ultimate 50th Floor Downtown Penthouse - 4000...,95625271612,VERIFIED,unknown,Manhattan,SoHo,40.72318,-74.00223,United States,US,False,flexible,Entire home/apt,2020.0,"$1,043",$209,2.0,21.0
102044,Lovely Two Bedroom & Event Space From Nonprofit,83006936257,VERIFIED,unknown,Brooklyn,Bedford-Stuyvesant,40.69095,-73.93444,United States,US,False,flexible,Entire home/apt,2010.0,$809,$162,31.0,4.0

In [80]:
data["instant_bookable"].apply(lambda x:1 if x==True else 0) # making it keep loopin and whenever i find True iam gonna make it 1 else 0

0         0
1         0
2         1
3         1
4         0
         ..
102040    1
102041    1
102042    0
102043    0
102044    0
Name: instant_bookable, Length: 100793, dtype: int64

In [84]:
data["instant_bookable"]=data["instant_bookable"].apply(lambda x:1 if x==True else 0) # for applying changes on our dataset

In [90]:
data["instant_bookable"].head(22)
# the index having a problem it keeps jumping so we have to reset it 
data.reset_index(inplace=True)

In [92]:
data["instant_bookable"].head(22)

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     1
9     0
10    0
11    1
12    0
13    1
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
Name: instant_bookable, dtype: int64

In [93]:
data

,index,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews
0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,$966,$193,10.0,9.0
1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
2,2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,UNKNOWN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,1,flexible,Private room,2005.0,$620,$124,3.0,0.0
3,3,unknown,85098326012,UNCONFIRMED,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,1,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0
4,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100788,102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,$982,$196,1.0,239.0
100789,102041,Cozy home away from home,60176837202,VERIFIED,unknown,Queens,Edgemere,40.59380,-73.77373,United States,US,1,moderate,Private room,2020.0,$946,$189,1.0,76.0
100790,102042,Central Park Views - Private Room & Bathroom,68411243647,VERIFIED,unknown,Manhattan,Upper West Side,40.79712,-73.96117,United States,US,0,strict,Private room,2012.0,$706,$141,1.0,4.0
100791,102043,Ultimate 50th Floor Downtown Penthouse - 4000...,95625271612,VERIFIED,unknown,Manhattan,SoHo,40.72318,-74.00223,United States,US,0,flexible,Entire home/apt,2020.0,"$1,043",$209,2.0,21.0
100792,102044,Lovely Two Bedroom & Event Space From Nonprofit,83006936257,VERIFIED,unknown,Brooklyn,Bedford-Stuyvesant,40.69095,-73.93444,United States,US,0,flexible,Entire home/apt,2010.0,$809,$162,31.0,4.0

In [97]:
type(data["price"][15]) # str column

str

In [98]:
data["price"].head(5)

0    $966
1    $142
2    $620
3    $368
4    $204
Name: price, dtype: object

In [102]:
data["price"]=data["price"].str.replace("$","") # replacing the $ sign so i can replace the datatype from str to int

In [103]:
data["price"]

0           966
1           142
2           620
3           368
4           204
           ...
100788      982
100789      946
100790      706
100791    1,043
100792      809
Name: price, Length: 100793, dtype: object

In [106]:
data["price"]=data["price"].str.replace(",","") # also replacing the ','

In [105]:
data["price"]

0          966
1          142
2          620
3          368
4          204
          ...
100788     982
100789     946
100790     706
100791    1043
100792     809
Name: price, Length: 100793, dtype: object

In [109]:
data["price"][15] # there is a space so we needa remove that space

'281 '

In [110]:
data["price"]=data["price"].str.replace(" ","")

In [112]:
data["price"][15] # removed the space done

'281'

In [114]:
data["price"].astype(int)[15] # now the column became int n converted it from str to int

np.int64(281)

In [115]:
data["price"]=data["price"].astype(int)

In [117]:
type(data["price"][1]) # now its int

numpy.int64

In [118]:
data.to_csv("Cleaned_AirBnb.csv")

In [120]:
pd.read_csv("Cleaned_AirBnb.csv") # cleaned csv file

,Unnamed: 0,index,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews
0,0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,966,$193,10.0,9.0
1,1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,142,$28,30.0,45.0
2,2,2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,UNKNOWN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,1,flexible,Private room,2005.0,620,$124,3.0,0.0
3,3,3,unknown,85098326012,UNCONFIRMED,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,1,moderate,Entire home/apt,2005.0,368,$74,30.0,270.0
4,4,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,204,$41,10.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100788,100788,102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,982,$196,1.0,239.0
100789,100789,102041,Cozy home away from home,60176837202,VERIFIED,unknown,Queens,Edgemere,40.59380,-73.77373,United States,US,1,moderate,Private room,2020.0,946,$189,1.0,76.0
100790,100790,102042,Central Park Views - Private Room & Bathroom,68411243647,VERIFIED,unknown,Manhattan,Upper West Side,40.79712,-73.96117,United States,US,0,strict,Private room,2012.0,706,$141,1.0,4.0
100791,100791,102043,Ultimate 50th Floor Downtown Penthouse - 4000...,95625271612,VERIFIED,unknown,Manhattan,SoHo,40.72318,-74.00223,United States,US,0,flexible,Entire home/apt,2020.0,1043,$209,2.0,21.0
100792,100792,102044,Lovely Two Bedroom & Event Space From Nonprofit,83006936257,VERIFIED,unknown,Brooklyn,Bedford-Stuyvesant,40.69095,-73.93444,United States,US,0,flexible,Entire home/apt,2010.0,809,$162,31.0,4.0

In [121]:
data.to_csv("cleaned_Data_index",index=False)

In [122]:
pd.read_csv("cleaned_Data_index")

,index,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews
0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,966,$193,10.0,9.0
1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,142,$28,30.0,45.0
2,2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,UNKNOWN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,1,flexible,Private room,2005.0,620,$124,3.0,0.0
3,3,unknown,85098326012,UNCONFIRMED,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,1,moderate,Entire home/apt,2005.0,368,$74,30.0,270.0
4,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,204,$41,10.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100788,102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,982,$196,1.0,239.0
100789,102041,Cozy home away from home,60176837202,VERIFIED,unknown,Queens,Edgemere,40.59380,-73.77373,United States,US,1,moderate,Private room,2020.0,946,$189,1.0,76.0
100790,102042,Central Park Views - Private Room & Bathroom,68411243647,VERIFIED,unknown,Manhattan,Upper West Side,40.79712,-73.96117,United States,US,0,strict,Private room,2012.0,706,$141,1.0,4.0
100791,102043,Ultimate 50th Floor Downtown Penthouse - 4000...,95625271612,VERIFIED,unknown,Manhattan,SoHo,40.72318,-74.00223,United States,US,0,flexible,Entire home/apt,2020.0,1043,$209,2.0,21.0
100792,102044,Lovely Two Bedroom & Event Space From Nonprofit,83006936257,VERIFIED,unknown,Brooklyn,Bedford-Stuyvesant,40.69095,-73.93444,United States,US,0,flexible,Entire home/apt,2010.0,809,$162,31.0,4.0

In [127]:
data.drop(columns=["index"],inplace=True)

KeyError: "['index'] not found in axis"

In [126]:
data

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,142,$28,30.0,45.0
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,UNKNOWN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,1,flexible,Private room,2005.0,620,$124,3.0,0.0
3,unknown,85098326012,UNCONFIRMED,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,1,moderate,Entire home/apt,2005.0,368,$74,30.0,270.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,204,$41,10.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100788,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,982,$196,1.0,239.0
100789,Cozy home away from home,60176837202,VERIFIED,unknown,Queens,Edgemere,40.59380,-73.77373,United States,US,1,moderate,Private room,2020.0,946,$189,1.0,76.0
100790,Central Park Views - Private Room & Bathroom,68411243647,VERIFIED,unknown,Manhattan,Upper West Side,40.79712,-73.96117,United States,US,0,strict,Private room,2012.0,706,$141,1.0,4.0
100791,Ultimate 50th Floor Downtown Penthouse - 4000...,95625271612,VERIFIED,unknown,Manhattan,SoHo,40.72318,-74.00223,United States,US,0,flexible,Entire home/apt,2020.0,1043,$209,2.0,21.0
100792,Lovely Two Bedroom & Event Space From Nonprofit,83006936257,VERIFIED,unknown,Brooklyn,Bedford-Stuyvesant,40.69095,-73.93444,United States,US,0,flexible,Entire home/apt,2010.0,809,$162,31.0,4.0

In [129]:
data.to_csv("cleaned_Data_index",index=False)

In [130]:
pd.read_csv("cleaned_Data_index")

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,142,$28,30.0,45.0
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,UNKNOWN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,1,flexible,Private room,2005.0,620,$124,3.0,0.0
3,unknown,85098326012,UNCONFIRMED,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,1,moderate,Entire home/apt,2005.0,368,$74,30.0,270.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,204,$41,10.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100788,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,982,$196,1.0,239.0
100789,Cozy home away from home,60176837202,VERIFIED,unknown,Queens,Edgemere,40.59380,-73.77373,United States,US,1,moderate,Private room,2020.0,946,$189,1.0,76.0
100790,Central Park Views - Private Room & Bathroom,68411243647,VERIFIED,unknown,Manhattan,Upper West Side,40.79712,-73.96117,United States,US,0,strict,Private room,2012.0,706,$141,1.0,4.0
100791,Ultimate 50th Floor Downtown Penthouse - 4000...,95625271612,VERIFIED,unknown,Manhattan,SoHo,40.72318,-74.00223,United States,US,0,flexible,Entire home/apt,2020.0,1043,$209,2.0,21.0
100792,Lovely Two Bedroom & Event Space From Nonprofit,83006936257,VERIFIED,unknown,Brooklyn,Bedford-Stuyvesant,40.69095,-73.93444,United States,US,0,flexible,Entire home/apt,2010.0,809,$162,31.0,4.0

In [132]:
data.to_excel("Excel_cleaned.xlsx")

In [ ]:
pd.read_excel("Excel_cleaned.xlsx")