In [39]:
import pandas as pd
import numpy as np

In [40]:
data=pd.read_csv("Original_data_with_more_rows.csv")

In [41]:
data.head(5)

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,MathScore,ReadingScore,WritingScore
0,0,female,group B,bachelor's degree,standard,none,72,72,74
1,1,female,group C,some college,standard,completed,69,90,88
2,2,female,group B,master's degree,standard,none,90,95,93
3,3,male,group A,associate's degree,free/reduced,none,47,57,44
4,4,male,group C,some college,standard,none,76,78,75

In [42]:
data.tail(5)

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,MathScore,ReadingScore,WritingScore
30636,995,male,group C,some high school,standard,none,56,47,51
30637,996,male,group E,associate's degree,free/reduced,none,74,75,72
30638,997,male,group C,some college,standard,none,36,29,27
30639,998,male,group A,some high school,free/reduced,completed,43,34,39
30640,999,female,group D,associate's degree,standard,none,52,68,66

In [43]:
data.shape # we have 3k rows and 9 columns

(30641, 9)

In [44]:
data.columns

Index(['Unnamed: 0', 'Gender', 'EthnicGroup', 'ParentEduc', 'LunchType',
       'TestPrep', 'MathScore', 'ReadingScore', 'WritingScore'],
      dtype='object')

In [45]:
data.info() # we have object,and int64 ,memory usage : 2.1+ MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30641 entries, 0 to 30640
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    30641 non-null  int64
 1   Gender        30641 non-null  object
 2   EthnicGroup   30641 non-null  object
 3   ParentEduc    30641 non-null  object
 4   LunchType     30641 non-null  object
 5   TestPrep      30641 non-null  object
 6   MathScore     30641 non-null  int64
 7   ReadingScore  30641 non-null  int64
 8   WritingScore  30641 non-null  int64
dtypes: int64(4), object(5)
memory usage: 2.1+ MB

In [46]:
data.head()

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,MathScore,ReadingScore,WritingScore
0,0,female,group B,bachelor's degree,standard,none,72,72,74
1,1,female,group C,some college,standard,completed,69,90,88
2,2,female,group B,master's degree,standard,none,90,95,93
3,3,male,group A,associate's degree,free/reduced,none,47,57,44
4,4,male,group C,some college,standard,none,76,78,75

In [47]:
data.columns

Index(['Unnamed: 0', 'Gender', 'EthnicGroup', 'ParentEduc', 'LunchType',
       'TestPrep', 'MathScore', 'ReadingScore', 'WritingScore'],
      dtype='object')

In [48]:
Dropped_columns=["Unnamed: 0",'EthnicGroup','LunchType']

In [49]:
data.drop(columns=Dropped_columns,inplace=True) # droppin the unwanted columns from our dataset

In [50]:
data

,Gender,ParentEduc,TestPrep,MathScore,ReadingScore,WritingScore
0,female,bachelor's degree,none,72,72,74
1,female,some college,completed,69,90,88
2,female,master's degree,none,90,95,93
3,male,associate's degree,none,47,57,44
4,male,some college,none,76,78,75
...,...,...,...,...,...,...
30636,male,some high school,none,56,47,51
30637,male,associate's degree,none,74,75,72
30638,male,some college,none,36,29,27
30639,male,some high school,completed,43,34,39
30640,female,associate's degree,none,52,68,66

In [51]:
data

,Gender,ParentEduc,TestPrep,MathScore,ReadingScore,WritingScore
0,female,bachelor's degree,none,72,72,74
1,female,some college,completed,69,90,88
2,female,master's degree,none,90,95,93
3,male,associate's degree,none,47,57,44
4,male,some college,none,76,78,75
...,...,...,...,...,...,...
30636,male,some high school,none,56,47,51
30637,male,associate's degree,none,74,75,72
30638,male,some college,none,36,29,27
30639,male,some high school,completed,43,34,39
30640,female,associate's degree,none,52,68,66

In [52]:
data.rename(columns={"ParentEduc":"Parent_Education","TestPrep":"Test_Preperation"},inplace=True)

In [53]:
data

,Gender,Parent_Education,Test_Preperation,MathScore,ReadingScore,WritingScore
0,female,bachelor's degree,none,72,72,74
1,female,some college,completed,69,90,88
2,female,master's degree,none,90,95,93
3,male,associate's degree,none,47,57,44
4,male,some college,none,76,78,75
...,...,...,...,...,...,...
30636,male,some high school,none,56,47,51
30637,male,associate's degree,none,74,75,72
30638,male,some college,none,36,29,27
30639,male,some high school,completed,43,34,39
30640,female,associate's degree,none,52,68,66

In [54]:
data.duplicated().sum() # we r having 1356 duplicated

np.int64(1356)

In [55]:
data.drop_duplicates(inplace=True) # dropping the duplicated

In [56]:
data.duplicated().sum() # now we dont have any duplicated

np.int64(0)

In [57]:
data # we r having index problem so we needa reset the index

,Gender,Parent_Education,Test_Preperation,MathScore,ReadingScore,WritingScore
0,female,bachelor's degree,none,72,72,74
1,female,some college,completed,69,90,88
2,female,master's degree,none,90,95,93
3,male,associate's degree,none,47,57,44
4,male,some college,none,76,78,75
...,...,...,...,...,...,...
30635,male,some high school,completed,64,59,64
30636,male,some high school,none,56,47,51
30638,male,some college,none,36,29,27
30639,male,some high school,completed,43,34,39
30640,female,associate's degree,none,52,68,66

In [58]:
data=data.reset_index().drop(columns="index")  # after resiting the index we dropped the index column that created

In [59]:
data

,Gender,Parent_Education,Test_Preperation,MathScore,ReadingScore,WritingScore
0,female,bachelor's degree,none,72,72,74
1,female,some college,completed,69,90,88
2,female,master's degree,none,90,95,93
3,male,associate's degree,none,47,57,44
4,male,some college,none,76,78,75
...,...,...,...,...,...,...
29280,male,some high school,completed,64,59,64
29281,male,some high school,none,56,47,51
29282,male,some college,none,36,29,27
29283,male,some high school,completed,43,34,39
29284,female,associate's degree,none,52,68,66

In [60]:
data

,Gender,Parent_Education,Test_Preperation,MathScore,ReadingScore,WritingScore
0,female,bachelor's degree,none,72,72,74
1,female,some college,completed,69,90,88
2,female,master's degree,none,90,95,93
3,male,associate's degree,none,47,57,44
4,male,some college,none,76,78,75
...,...,...,...,...,...,...
29280,male,some high school,completed,64,59,64
29281,male,some high school,none,56,47,51
29282,male,some college,none,36,29,27
29283,male,some high school,completed,43,34,39
29284,female,associate's degree,none,52,68,66

In [61]:
data.isna().sum() # we dont have null values

Gender              0
Parent_Education    0
Test_Preperation    0
MathScore           0
ReadingScore        0
WritingScore        0
dtype: int64

In [62]:
data.dropna(inplace=True) # we did that so we can make sure we dont have null values

In [63]:
data

,Gender,Parent_Education,Test_Preperation,MathScore,ReadingScore,WritingScore
0,female,bachelor's degree,none,72,72,74
1,female,some college,completed,69,90,88
2,female,master's degree,none,90,95,93
3,male,associate's degree,none,47,57,44
4,male,some college,none,76,78,75
...,...,...,...,...,...,...
29280,male,some high school,completed,64,59,64
29281,male,some high school,none,56,47,51
29282,male,some college,none,36,29,27
29283,male,some high school,completed,43,34,39
29284,female,associate's degree,none,52,68,66

In [ ]:
# we wanna make f for female and m for male
data["Gender"]=data["Gender"].replace({"Female":"F","Male":"M"})

In [67]:
data

,Gender,Parent_Education,Test_Preperation,MathScore,ReadingScore,WritingScore
0,M,bachelor's degree,none,72,72,74
1,M,some college,completed,69,90,88
2,M,master's degree,none,90,95,93
3,M,associate's degree,none,47,57,44
4,M,some college,none,76,78,75
...,...,...,...,...,...,...
29280,M,some high school,completed,64,59,64
29281,M,some high school,none,56,47,51
29282,M,some college,none,36,29,27
29283,M,some high school,completed,43,34,39
29284,M,associate's degree,none,52,68,66

In [68]:
data

,Gender,Parent_Education,Test_Preperation,MathScore,ReadingScore,WritingScore
0,M,bachelor's degree,none,72,72,74
1,M,some college,completed,69,90,88
2,M,master's degree,none,90,95,93
3,M,associate's degree,none,47,57,44
4,M,some college,none,76,78,75
...,...,...,...,...,...,...
29280,M,some high school,completed,64,59,64
29281,M,some high school,none,56,47,51
29282,M,some college,none,36,29,27
29283,M,some high school,completed,43,34,39
29284,M,associate's degree,none,52,68,66

In [81]:
70*3

210

In [72]:
data["Total Score"]=data["MathScore"]+data["ReadingScore"]+data["WritingScore"]

In [75]:
data.drop(columns="Total SCore",inplace=True)

In [76]:
data

,Gender,Parent_Education,Test_Preperation,MathScore,ReadingScore,WritingScore,Total Score
0,M,bachelor's degree,none,72,72,74,218
1,M,some college,completed,69,90,88,247
2,M,master's degree,none,90,95,93,278
3,M,associate's degree,none,47,57,44,148
4,M,some college,none,76,78,75,229
...,...,...,...,...,...,...,...
29280,M,some high school,completed,64,59,64,187
29281,M,some high school,none,56,47,51,154
29282,M,some college,none,36,29,27,92
29283,M,some high school,completed,43,34,39,116
29284,M,associate's degree,none,52,68,66,186

In [82]:
data["Success"]=data["Total Score"].apply(lambda i : "Success" if i > 210 else "Fail")

In [83]:
data

,Gender,Parent_Education,Test_Preperation,MathScore,ReadingScore,WritingScore,Total Score,Success
0,M,bachelor's degree,none,72,72,74,218,Success
1,M,some college,completed,69,90,88,247,Success
2,M,master's degree,none,90,95,93,278,Success
3,M,associate's degree,none,47,57,44,148,Fail
4,M,some college,none,76,78,75,229,Success
...,...,...,...,...,...,...,...,...
29280,M,some high school,completed,64,59,64,187,Fail
29281,M,some high school,none,56,47,51,154,Fail
29282,M,some college,none,36,29,27,92,Fail
29283,M,some high school,completed,43,34,39,116,Fail
29284,M,associate's degree,none,52,68,66,186,Fail

In [84]:
data["Success"].value_counts() # this is gonna give us the amount of success and the amount of fail

Success
Fail       15923
Success    13362
Name: count, dtype: int64

In [85]:
data.to_excel("DataCleaned.xlsx",index=False)