In [1018]:
import pandas as pd
import numpy as np

In [1019]:
Data=pd.read_csv("amazon_product.csv")
Data

,Unnamed: 0,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
0,0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,https://www.amazon.com/dp/B0BQ118F2T,https://m.media-amazon.com/images/I/61K1Fz5Lxv...,...,False,False,True,False,6K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
1,1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,https://www.amazon.com/dp/B0CTD47P22,https://m.media-amazon.com/images/I/51QhB2CfqS...,...,False,False,True,False,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",False,Only 7 left in stock - order soon.,NaN,NaN
2,2,B0CHH6X6H2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,https://www.amazon.com/dp/B0CHH6X6H2,https://m.media-amazon.com/images/I/812woqv69C...,...,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Aug 6",False,NaN,NaN,NaN
3,3,B0BZ9XNBRB,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,https://www.amazon.com/dp/B0BZ9XNBRB,https://m.media-amazon.com/images/I/61r7cCpQPl...,...,False,False,False,False,10K+ bought in past month,FREE delivery Aug 6 - 8,True,NaN,NaN,NaN
4,4,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.1,423,https://www.amazon.com/dp/B0CN1QSH8Q,https://m.media-amazon.com/images/I/61s0ZzwzSC...,...,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,59,B0D6LWXK1R,Greatish Hits: I Followed My Dreams and My Dre...,$34.98,NaN,USD,NaN,0,https://www.amazon.com/dp/B0D6LWXK1R,https://m.media-amazon.com/images/I/815otxMW0i...,...,False,False,False,False,50+ bought in past month,FREE delivery on $35 shipped by Amazon.This ti...,False,NaN,NaN,NaN
60,60,B0CLKQF5HR,Swan Song,$14.99,$30.00,USD,4.4,14471,https://www.amazon.com/dp/B0CLKQF5HR,https://m.media-amazon.com/images/I/71dSn3QCY6...,...,True,False,False,False,Print List Price:,Available instantly,False,NaN,NaN,NaN
61,61,B0BZFHK12K,Bluey: Let&#x27;s Play!,$0.00,NaN,USD,3.5,270,https://www.amazon.com/dp/B0BZFHK12K,https://m.media-amazon.com/images/I/617GUqQEIC...,...,False,False,False,False,"Jul 7, 2023",Available instantly on compatible devices,False,NaN,NaN,NaN
62,62,B09Z7J4L6X,Xbox Wireless Controller – Sky Cipher Special ...,$69.99,NaN,USD,2.6,12,https://www.amazon.com/dp/B09Z7J4L6X,https://m.media-amazon.com/images/I/71i2tEKlZ2...,...,True,False,False,False,"Aug 13, 2024",FREE deliveryThis item will be released on Aug...,False,NaN,NaN,NaN
63,63,B0CT2R7199,HP DeskJet 2855e Wireless All-in-One Color Ink...,$59.99,$84.99,USD,4.0,48154,https://www.amazon.com/dp/B0CT2R7199,https://m.media-amazon.com/images/I/61+biEwB1h...,...,True,False,False,True,80K+ bought in past month,FREE delivery,False,NaN,NaN,NaN

In [1020]:
Data.head(5)

,Unnamed: 0,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
0,0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,https://www.amazon.com/dp/B0BQ118F2T,https://m.media-amazon.com/images/I/61K1Fz5Lxv...,...,False,False,True,False,6K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
1,1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,https://www.amazon.com/dp/B0CTD47P22,https://m.media-amazon.com/images/I/51QhB2CfqS...,...,False,False,True,False,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",False,Only 7 left in stock - order soon.,NaN,NaN
2,2,B0CHH6X6H2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,https://www.amazon.com/dp/B0CHH6X6H2,https://m.media-amazon.com/images/I/812woqv69C...,...,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Aug 6",False,NaN,NaN,NaN
3,3,B0BZ9XNBRB,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,https://www.amazon.com/dp/B0BZ9XNBRB,https://m.media-amazon.com/images/I/61r7cCpQPl...,...,False,False,False,False,10K+ bought in past month,FREE delivery Aug 6 - 8,True,NaN,NaN,NaN
4,4,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.1,423,https://www.amazon.com/dp/B0CN1QSH8Q,https://m.media-amazon.com/images/I/61s0ZzwzSC...,...,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN

In [1021]:
Data.tail()

,Unnamed: 0,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
59,59,B0D6LWXK1R,Greatish Hits: I Followed My Dreams and My Dre...,$34.98,NaN,USD,NaN,0,https://www.amazon.com/dp/B0D6LWXK1R,https://m.media-amazon.com/images/I/815otxMW0i...,...,False,False,False,False,50+ bought in past month,FREE delivery on $35 shipped by Amazon.This ti...,False,NaN,NaN,NaN
60,60,B0CLKQF5HR,Swan Song,$14.99,$30.00,USD,4.4,14471,https://www.amazon.com/dp/B0CLKQF5HR,https://m.media-amazon.com/images/I/71dSn3QCY6...,...,True,False,False,False,Print List Price:,Available instantly,False,NaN,NaN,NaN
61,61,B0BZFHK12K,Bluey: Let&#x27;s Play!,$0.00,NaN,USD,3.5,270,https://www.amazon.com/dp/B0BZFHK12K,https://m.media-amazon.com/images/I/617GUqQEIC...,...,False,False,False,False,"Jul 7, 2023",Available instantly on compatible devices,False,NaN,NaN,NaN
62,62,B09Z7J4L6X,Xbox Wireless Controller – Sky Cipher Special ...,$69.99,NaN,USD,2.6,12,https://www.amazon.com/dp/B09Z7J4L6X,https://m.media-amazon.com/images/I/71i2tEKlZ2...,...,True,False,False,False,"Aug 13, 2024",FREE deliveryThis item will be released on Aug...,False,NaN,NaN,NaN
63,63,B0CT2R7199,HP DeskJet 2855e Wireless All-in-One Color Ink...,$59.99,$84.99,USD,4.0,48154,https://www.amazon.com/dp/B0CT2R7199,https://m.media-amazon.com/images/I/61+biEwB1h...,...,True,False,False,True,80K+ bought in past month,FREE delivery,False,NaN,NaN,NaN

In [1022]:
type(Data["product_price"][0]) # this is a str n thats a problem

str

In [1023]:
Data.columns

Index(['Unnamed: 0', 'asin', 'product_title', 'product_price',
       'product_original_price', 'currency', 'product_star_rating',
       'product_num_ratings', 'product_url', 'product_photo',
       'product_num_offers', 'product_minimum_offer_price', 'is_best_seller',
       'is_amazon_choice', 'is_prime', 'climate_pledge_friendly',
       'sales_volume', 'delivery', 'has_variations', 'product_availability',
       'unit_price', 'unit_count'],
      dtype='object')

In [1024]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   64 non-null     int64
 1   asin                         64 non-null     object
 2   product_title                64 non-null     object
 3   product_price                64 non-null     object
 4   product_original_price       27 non-null     object
 5   currency                     64 non-null     object
 6   product_star_rating          54 non-null     float64
 7   product_num_ratings          64 non-null     int64
 8   product_url                  64 non-null     object
 9   product_photo                64 non-null     object
 10  product_num_offers           64 non-null     int64
 11  product_minimum_offer_price  64 non-null     object
 12  is_best_seller               64 non-null     bool
 13  is_amazon_choice             64 non-null     bool
 14  is_prime                     64 non-null     bool
 15  climate_pledge_friendly      64 non-null     bool
 16  sales_volume                 61 non-null     object
 17  delivery                     63 non-null     object
 18  has_variations               64 non-null     bool
 19  product_availability         1 non-null      object
 20  unit_price                   5 non-null      object
 21  unit_count                   5 non-null      float64
dtypes: bool(5), float64(2), int64(3), object(12)
memory usage: 8.9+ KB

In [1025]:
Data.head()

,Unnamed: 0,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
0,0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,https://www.amazon.com/dp/B0BQ118F2T,https://m.media-amazon.com/images/I/61K1Fz5Lxv...,...,False,False,True,False,6K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
1,1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,https://www.amazon.com/dp/B0CTD47P22,https://m.media-amazon.com/images/I/51QhB2CfqS...,...,False,False,True,False,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",False,Only 7 left in stock - order soon.,NaN,NaN
2,2,B0CHH6X6H2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,https://www.amazon.com/dp/B0CHH6X6H2,https://m.media-amazon.com/images/I/812woqv69C...,...,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Aug 6",False,NaN,NaN,NaN
3,3,B0BZ9XNBRB,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,https://www.amazon.com/dp/B0BZ9XNBRB,https://m.media-amazon.com/images/I/61r7cCpQPl...,...,False,False,False,False,10K+ bought in past month,FREE delivery Aug 6 - 8,True,NaN,NaN,NaN
4,4,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.1,423,https://www.amazon.com/dp/B0CN1QSH8Q,https://m.media-amazon.com/images/I/61s0ZzwzSC...,...,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN

In [1026]:
Data.columns

Index(['Unnamed: 0', 'asin', 'product_title', 'product_price',
       'product_original_price', 'currency', 'product_star_rating',
       'product_num_ratings', 'product_url', 'product_photo',
       'product_num_offers', 'product_minimum_offer_price', 'is_best_seller',
       'is_amazon_choice', 'is_prime', 'climate_pledge_friendly',
       'sales_volume', 'delivery', 'has_variations', 'product_availability',
       'unit_price', 'unit_count'],
      dtype='object')

In [1027]:
Data.drop(columns=['Unnamed: 0','asin','product_url', 'product_photo','product_num_offers', 'product_minimum_offer_price', 'is_amazon_choice', 'is_prime', 'climate_pledge_friendly',
'sales_volume', 'delivery', 'has_variations'],inplace=True)

In [1028]:
Data.head(5)

,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,is_best_seller,product_availability,unit_price,unit_count
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,False,NaN,NaN,NaN
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,False,Only 7 left in stock - order soon.,NaN,NaN
2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,False,NaN,NaN,NaN
3,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,False,NaN,NaN,NaN
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.1,423,False,NaN,NaN,NaN

In [1029]:
Data.columns

Index(['product_title', 'product_price', 'product_original_price', 'currency',
       'product_star_rating', 'product_num_ratings', 'is_best_seller',
       'product_availability', 'unit_price', 'unit_count'],
      dtype='object')

In [1030]:
newCol=[]
for i in Data.columns:
    newCol.append(i.capitalize())

In [1031]:
Data.columns=newCol

In [1032]:
Data

,Product_title,Product_price,Product_original_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller,Product_availability,Unit_price,Unit_count
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,False,NaN,NaN,NaN
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,False,Only 7 left in stock - order soon.,NaN,NaN
2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,False,NaN,NaN,NaN
3,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,False,NaN,NaN,NaN
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.1,423,False,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
59,Greatish Hits: I Followed My Dreams and My Dre...,$34.98,NaN,USD,NaN,0,False,NaN,NaN,NaN
60,Swan Song,$14.99,$30.00,USD,4.4,14471,True,NaN,NaN,NaN
61,Bluey: Let&#x27;s Play!,$0.00,NaN,USD,3.5,270,False,NaN,NaN,NaN
62,Xbox Wireless Controller – Sky Cipher Special ...,$69.99,NaN,USD,2.6,12,True,NaN,NaN,NaN
63,HP DeskJet 2855e Wireless All-in-One Color Ink...,$59.99,$84.99,USD,4.0,48154,True,NaN,NaN,NaN

In [1033]:
Data.duplicated().sum() # we dont have any duplicated columns

np.int64(0)

In [1034]:
# Data.drop_duplicates(inplace=True) if we have any duplicates

In [1035]:
Data.isna().sum() # checking the null values

Product_title              0
Product_price              0
Product_original_price    37
Currency                   0
Product_star_rating       10
Product_num_ratings        0
Is_best_seller             0
Product_availability      63
Unit_price                59
Unit_count                59
dtype: int64

In [1036]:
Data.shape

(64, 10)

In [1037]:
Data=Data[['Product_title',"Product_price","Currency","Product_star_rating","Product_num_ratings","Is_best_seller"]] # filtering the data n taking the columns i need for my analysis later

In [1038]:
Data.isna().sum()

Product_title           0
Product_price           0
Currency                0
Product_star_rating    10
Product_num_ratings     0
Is_best_seller          0
dtype: int64

In [1039]:
Data.head()

,Product_title,Product_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,USD,4.0,2929,False
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,USD,4.2,135,False
2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,USD,3.9,205,False
3,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,USD,4.3,2248,False
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,USD,4.1,423,False

In [1040]:
Data.dropna(inplace=True)

C:\Users\Office\AppData\Local\Temp\ipykernel_20732\2081895645.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data.dropna(inplace=True)

In [1041]:
Data.isna().sum() # now we dont have any null values

Product_title          0
Product_price          0
Currency               0
Product_star_rating    0
Product_num_ratings    0
Is_best_seller         0
dtype: int64

In [1042]:
Data.head(3)

,Product_title,Product_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,USD,4.0,2929,False
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,USD,4.2,135,False
2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,USD,3.9,205,False

In [1043]:
Data["Is_best_seller"].unique() # we have True and False

array([False,  True])

In [1044]:
Data["Is_best_seller"]=Data["Is_best_seller"].apply(lambda x:1 if x==True else 0) # turning the True and False into zeros and ones so we can upload that to our machine learning model later

C:\Users\Office\AppData\Local\Temp\ipykernel_20732\164773122.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data["Is_best_seller"]=Data["Is_best_seller"].apply(lambda x:1 if x==True else 0) # turning the True and False into zeros and ones so we can upload that to our machine learning model later

In [1045]:
Data.head(20)

,Product_title,Product_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,USD,4.0,2929,0
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,USD,4.2,135,0
2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,USD,3.9,205,0
3,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,USD,4.3,2248,0
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,USD,4.1,423,0
5,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",$129.99,USD,4.2,578,0
6,"SAMSUNG Galaxy A35 5G A Series Cell Phone, 128...",$349.99,USD,4.4,109,0
7,TracFone | Motorola Moto g Pure | Locked | 32G...,$49.39,USD,4.2,2771,0
8,"SAMSUNG,Galaxy A04e (SM-A042M/DS) Dual SIM 32G...",$87.10,USD,3.9,613,0
9,Moto G Play | 2024 | Unlocked | Made for US 4/...,$129.99,USD,4.1,94,0
10,"Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...",$70.61,USD,3.9,462,0
11,AT&amp;T BL102-2 DECT 6.0 2-Handset Cordless P...,$48.75,USD,4.3,26685,1
12,Bold K10 | 2024 | 3-Day Battery | Unlocked | 6...,$99.99,USD,3.8,8,0
13,Google Pixel 8 - Unlocked Android Smartphone w...,$499.00,USD,4.3,2098,0
14,Motorola Moto G Power 5G | 2023 | Unlocked | M...,$199.99,USD,4.2,2258,0
15,VTech CS6719-2 2-Handset Expandable Cordless P...,$38.67,USD,4.4,37513,0
16,Apple AirTag,$23.99,USD,4.6,4355,0
17,Apple AirTag 4 pack,$84.99,USD,4.7,390,0
18,"Amazon Basics - Washable School Glue Sticks, D...",$0.25,USD,4.7,8010,0
19,Amazon Basics Heavy Duty Plastic Folders with ...,$0.49,USD,4.8,13638,1

In [1046]:
Data["Product_price"]=Data["Product_price"].str.replace("$","")

C:\Users\Office\AppData\Local\Temp\ipykernel_20732\1579096941.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data["Product_price"]=Data["Product_price"].str.replace("$","")

In [1047]:
Data["Product_price"]=Data["Product_price"].astype(float) # turning the product price from str to float then we r gonna turn it to int

C:\Users\Office\AppData\Local\Temp\ipykernel_20732\4083470683.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data["Product_price"]=Data["Product_price"].astype(float) # turning the product price from str to float then we r gonna turn it to int

In [1048]:
Data["Product_price"][0] # now its float

np.float64(99.99)

In [1049]:
Data["Product_price"]=Data["Product_price"].apply(lambda x:round(x))

C:\Users\Office\AppData\Local\Temp\ipykernel_20732\2730227331.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data["Product_price"]=Data["Product_price"].apply(lambda x:round(x))

In [1050]:
Data

,Product_title,Product_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,100,USD,4.0,2929,0
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",150,USD,4.2,135,0
2,Total by Verizon | Samsung Galaxy A03s | Locke...,50,USD,3.9,205,0
3,Google Pixel 7a - Unlocked Android Cell Phone ...,335,USD,4.3,2248,0
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",200,USD,4.1,423,0
5,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",130,USD,4.2,578,0
6,"SAMSUNG Galaxy A35 5G A Series Cell Phone, 128...",350,USD,4.4,109,0
7,TracFone | Motorola Moto g Pure | Locked | 32G...,49,USD,4.2,2771,0
8,"SAMSUNG,Galaxy A04e (SM-A042M/DS) Dual SIM 32G...",87,USD,3.9,613,0
9,Moto G Play | 2024 | Unlocked | Made for US 4/...,130,USD,4.1,94,0
10,"Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...",71,USD,3.9,462,0
11,AT&amp;T BL102-2 DECT 6.0 2-Handset Cordless P...,49,USD,4.3,26685,1
12,Bold K10 | 2024 | 3-Day Battery | Unlocked | 6...,100,USD,3.8,8,0
13,Google Pixel 8 - Unlocked Android Smartphone w...,499,USD,4.3,2098,0
14,Motorola Moto G Power 5G | 2023 | Unlocked | M...,200,USD,4.2,2258,0
15,VTech CS6719-2 2-Handset Expandable Cordless P...,39,USD,4.4,37513,0
16,Apple AirTag,24,USD,4.6,4355,0
17,Apple AirTag 4 pack,85,USD,4.7,390,0
18,"Amazon Basics - Washable School Glue Sticks, D...",0,USD,4.7,8010,0
19,Amazon Basics Heavy Duty Plastic Folders with ...,0,USD,4.8,13638,1
20,"Amazon Basics Multipurpose, Comfort Grip, PVD ...",2,USD,4.8,54922,1
21,The Book of Bill (Gravity Falls),18,USD,4.7,180,1
23,Peacock TV,0,USD,4.2,437768,0
24,Thanksgiving - UHD/BD Combo + Digital + Steelb...,56,USD,4.0,3075,1
25,"NESCAFÉ Gold Espresso Blonde, Instant Coffee, ...",7,USD,4.7,628,1
26,Hillbilly Elegy: A Memoir of a Family and Cult...,12,USD,4.4,100331,1
29,URO Vaginal Probiotics for Women pH Balance wi...,29,USD,4.5,1142,1
30,Going Balls: 3D Race,0,USD,4.7,8,0
31,Atomic Habits: An Easy &amp; Proven Way to Bui...,0,USD,4.8,130395,1
33,The Anxious Generation: How the Great Rewiring...,0,USD,4.7,2317,1
35,DAYBETTER LED Strip Lights 130ft (2 Rolls of 6...,13,USD,4.5,27686,0
36,Teacher Simulator: School Days,0,USD,3.2,9,0
37,"Bounty Select-A-Size Paper Towels, White, 8 Tr...",22,USD,4.8,36930,0
38,Apple AirPods Pro (2nd Generation) Wireless Ea...,180,USD,4.6,2687,0
39,Rand McNally Large Scale Road Atlas 2025,19,USD,4.7,793,1
41,EA SPORTS College Football 25 - PlayStation 5,67,USD,3.8,96,1
42,My Avatar Life City,0,USD,1.8,12,0
43,Max,0,USD,4.3,384756,0
44,Ragdoll Kick: Broken Bones,0,USD,4.4,38,0
45,It Ends with Us,0,USD,4.7,333273,1
47,What Now,12,USD,4.2,51,1
48,All the Colors of the Dark,0,USD,4.6,6346,1
49,In A Violent Nature: Collector’s Edition [Blu-...,30,USD,3.2,204,0
50,The God of the Woods: A Novel,15,USD,4.5,3241,1
51,"Hanes Men&#x27;s Pocket Undershirt Pack, Cotto...",22,USD,4.4,25391,0
54,Mission: Impossible - Dead Reckoning,6,USD,4.7,2440,0
55,Disney+,0,USD,4.4,1015448,0
56,Netflix,0,USD,4.6,447888,0
57,A Death in Cornwall: A Novel (Gabriel Allon Bo...,16,USD,4.6,7384,1
58,TikTok,0,USD,4.2,140637,0
60,Swan Song,15,USD,4.4,14471,1
61,Bluey: Let&#x27;s Play!,0,USD,3.5,270,0
62,Xbox Wireless Controller – Sky Cipher Special ...,70,USD,2.6,12,1
63,HP DeskJet 2855e Wireless All-in-One Color Ink...,60,USD,4.0,48154,1

In [1051]:
Data.to_excel("Cleaned_data.xlsx")